### ISSUE TITLE
Functional genomic hypothesis generation and experimentation by a robot scientist

### ISSUE THREAD

**Issue by agitter** [AccelerationConsortium/awesome-self-driving-labs#59]
This 2004 paper appears to meet modern defintions of a self-driving lab: https://www.nature.com/articles/nature02236

> The question of whether it is possible to automate the scientific process is of both great theoretical interest[1](https://www.nature.com/articles/nature02236#ref-CR1),[2](https://www.nature.com/articles/nature02236#ref-CR2) and increasing practical importance because, in many scientific areas, data are being generated much faster than they can be effectively analysed. We describe a physically implemented robotic system that applies techniques from artificial intelligence[3](https://www.nature.com/articles/nature02236#ref-CR3),[4](https://www.nature.com/articles/nature02236#ref-CR4),[5](https://www.nature.com/articles/nature02236#ref-CR5),[6](https://www.nature.com/articles/nature02236#ref-CR6),[7](https://www.nature.com/articles/nature02236#ref-CR7),[8](https://www.nature.com/articles/nature02236#ref-CR8) to carry out cycles of scientific experimentation. The system automatically originates hypotheses to explain observations, devises experiments to test these hypotheses, physically runs the experiments using a laboratory robot, interprets the results to falsify hypotheses inconsistent with the data, and then repeats the cycle. Here we apply the system to the determination of gene function using deletion mutants of yeast (Saccharomyces cerevisiae) and auxotrophic growth experiments[9](https://www.nature.com/articles/nature02236#ref-CR9). We built and tested a detailed logical model (involving genes, proteins and metabolites) of the aromatic amino acid synthesis pathway. In biological experiments that automatically reconstruct parts of this model, we show that an intelligent experiment selection strategy is competitive with human performance and significantly outperforms, with a cost decrease of 3-fold and 100-fold (respectively), both cheapest and random-experiment selection.

**Comment by sgbaird** [comment]
Closed by #60
